version: '3'

services:
  emailapi:
    image: email
    build:
      context: ./services
      dockerfile: email.Dockerfile
    ports:
      - "8082:80"
    depends_on:
        - mssql
        - rabbitmq
  userapi:
    image: user
    build:
      context: ./services
      dockerfile: user.Dockerfile
    ports:
      - "8081:80"
    depends_on:
        - mssql
        - rabbitmq
  workoutapi:
    image: workout
    build:
      context: ./services
      dockerfile: workout.Dockerfile
    ports:
      - "8083:80"
    depends_on:
        - mssql
  mssql:
    image: "lucas/mssql-server-linux"
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: my-rabbit
